"""initial_schema

Revision ID: 4805c133db8f
Revises: 
Create Date: 2026-06-01 03:21:52.483645
"""
from alembic import op
import sqlalchemy as sa


revision = '4805c133db8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('normal_side', sa.String(length=1), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pr_number')
    )
    op.create_table('uom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('ar_account_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ar_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('credit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'code', name='uq_location_code')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Integer(), nullable=False),
    sa.Column('ap_account_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ap_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('inventory_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adj_number', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('adj_date', sa.Date(), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('je_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['je_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adj_number')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('reorder_qty', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('preferred_supplier_id', sa.Integer(), nullable=True),
    sa.Column('valuation_method', sa.String(length=20), nullable=False),
    sa.Column('inventory_account_id', sa.Integer(), nullable=True),
    sa.Column('cogs_account_id', sa.Integer(), nullable=True),
    sa.Column('revenue_account_id', sa.Integer(), nullable=True),
    sa.Column('current_avg_cost', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cogs_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['inventory_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['preferred_supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['revenue_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['uom.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requisitions.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('so_number')
    )
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_number', sa.String(length=20), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_number')
    )
    op.create_table('goods_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_number', sa.String(length=20), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('supplier_ref', sa.String(length=60), nullable=True),
    sa.Column('je_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['je_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grn_number')
    )
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('txn_type', sa.String(length=30), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_line', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_it_date', 'inventory_transactions', ['txn_date'], unique=False)
    op.create_index('idx_it_product_loc', 'inventory_transactions', ['product_id', 'location_id'], unique=False)
    op.create_table('po_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_requested', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requisitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_number', sa.String(length=20), nullable=False),
    sa.Column('so_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ship_date', sa.Date(), nullable=False),
    sa.Column('carrier', sa.String(length=60), nullable=True),
    sa.Column('tracking_ref', sa.String(length=60), nullable=True),
    sa.Column('cogs_je_id', sa.Integer(), nullable=True),
    sa.Column('sales_je_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cogs_je_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['sales_je_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_number')
    )
    op.create_table('so_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('qty_shipped', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adjustment_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adj_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_system', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('qty_actual', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('it_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adj_id'], ['inventory_adjustments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['it_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fifo_layers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('grn_txn_id', sa.Integer(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('qty_remaining', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['grn_txn_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fl_product', 'fifo_layers', ['product_id', 'location_id', 'receipt_date'], unique=False)
    op.create_table('grn_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('it_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['it_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_number', sa.String(length=20), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('je_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_receipts.id'], ),
    sa.ForeignKeyConstraint(['je_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_number')
    )
    op.create_table('sales_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_number', sa.String(length=20), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('je_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['je_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_number')
    )
    op.create_table('shipment_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('so_line_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_shipped', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('it_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['it_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['so_line_id'], ['so_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inv_number', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('je_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_receipts.id'], ),
    sa.ForeignKeyConstraint(['je_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inv_number')
    )
    op.create_table('transfer_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('out_it_id', sa.Integer(), nullable=True),
    sa.Column('in_it_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['in_it_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['out_it_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_return_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('grn_line_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_returned', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['grn_line_id'], ['grn_lines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['purchase_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_return_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('shipment_line_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_returned', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['sales_returns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_line_id'], ['shipment_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_return_lines')
    op.drop_table('purchase_return_lines')
    op.drop_table('transfer_lines')
    op.drop_table('supplier_invoices')
    op.drop_table('shipment_lines')
    op.drop_table('sales_returns')
    op.drop_table('purchase_returns')
    op.drop_table('grn_lines')
    op.drop_index('idx_fl_product', table_name='fifo_layers')
    op.drop_table('fifo_layers')
    op.drop_table('adjustment_lines')
    op.drop_table('so_lines')
    op.drop_table('shipments')
    op.drop_table('pr_lines')
    op.drop_table('po_lines')
    op.drop_index('idx_it_product_loc', table_name='inventory_transactions')
    op.drop_index('idx_it_date', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_table('goods_receipts')
    op.drop_table('stock_transfers')
    op.drop_table('sales_orders')
    op.drop_table('purchase_orders')
    op.drop_table('products')
    op.drop_table('inventory_adjustments')
    op.drop_table('suppliers')
    op.drop_table('locations')
    op.drop_table('journal_lines')
    op.drop_table('customers')
    op.drop_table('warehouses')
    op.drop_table('users')
    op.drop_table('uom')
    op.drop_table('purchase_requisitions')
    op.drop_table('journal_entries')
    op.drop_table('accounts')
    # ### end Alembic commands ###
